apiVersion: v1
kind: PersistentVolume
metadata:
  name: moon-sqlite-pv-5gi
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /nfs/data/moon/sqlite
  storageClassName: {{ .Values.storageclass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moon-sqlite-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storageclass }}