{{- if .Values.moon.server }}
---
apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: {{ .Values.moon.server.serviceAccounts }} 
  namespace: {{ .Values.namespace }}
{{- end }}
{{- if .Values.moon.agent }} 
---
apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: {{ .Values.moon.agent.serviceAccounts }} 
  namespace: {{ .Values.namespace }}
{{- end }}